official composer CA bundle support
mhujer/fio-api-php pull request #7
Opened 2016-11-22 12:51 UTC by soukicz

2016-11-22 13:32 UTC, fprochazka commented on composer.json
> +    "kdyby/curl-ca-bundle": "Provides regularly updated root certificates list",
Would be better to remove the suggest altogether :)

2016-11-22 13:35 UTC, soukicz commented on composer.json
> +    "kdyby/curl-ca-bundle": "Provides regularly updated root certificates list",
Původně jsem chtěl, ale ty tam nemáš _abandoned_, tak jsem to ještě nechal.

2016-11-22 13:43 UTC, fprochazka commented on composer.json
> +    "kdyby/curl-ca-bundle": "Provides regularly updated root certificates list",
Na https://packagist.org/packages/kdyby/curl-ca-bundle mám

2016-11-22 14:11 UTC, soukicz commented on composer.json
> +    "kdyby/curl-ca-bundle": "Provides regularly updated root certificates list",
Divný, koukal jsem sem - https://github.com/Kdyby/CurlCaBundle/blob/master/composer.json

2016-11-22 14:14 UTC, soukicz commented on composer.json
> +    "kdyby/curl-ca-bundle": "Provides regularly updated root certificates list",
Tak a je fuč :) V kódu jsem to teda ještě nechal, ať se něco nerozbije.

2016-11-22 15:04 UTC, fprochazka commented on composer.json
> +    "kdyby/curl-ca-bundle": "Provides regularly updated root certificates list",
:+1:

2016-11-22 15:04 UTC, fprochazka commented on composer.json
> +    "kdyby/curl-ca-bundle": "Provides regularly updated root certificates list",
Oni na to mají UI, nemusíš to psát do `composer.json`

2016-11-22 15:21 UTC, mhujer requested changes

2016-11-22 15:21 UTC, mhujer commented on src/FioApi/Downloader.php
> +        if(class_exists('\Composer\CaBundle\CaBundle')) {
there should be a space after `if`

2016-11-22 15:21 UTC, mhujer commented on src/FioApi/Downloader.php
> +        } elseif(class_exists('\Kdyby\CurlCaBundle\CertificateHelper')) {
and after `elseif`

2016-11-22 15:34 UTC, mhujer commented on composer.json
> +    "kdyby/curl-ca-bundle": "Provides regularly updated root certificates list",
👍

2016-11-24 13:35 UTC, mhujer commented
merged manually (I've fixed-up the cs fix), thanks!

2016-11-24 13:35 UTC, closed without merging